# Generated by Django 6.0.1 on 2026-01-18 05:41

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("farmer", "Agriculteur"),
                            ("buyer", "Acheteur"),
                            ("admin", "Administrateur"),
                        ],
                        default="buyer",
                        max_length=10,
                        verbose_name="Type d'utilisateur",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Numéro de téléphone invalide. Format: +222XXXXXXXX ou 00222XXXXXXXX (8 chiffres)",
                                regex="^(\\+222|00222)?[0-9]{8}$",
                            )
                        ],
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "wilaya",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Nouakchott", "Nouakchott"),
                            ("Nouakchott Ouest", "Nouakchott Ouest"),
                            ("Nouakchott Nord", "Nouakchott Nord"),
                            ("Nouakchott Sud", "Nouakchott Sud"),
                            ("Brakna", "Brakna"),
                            ("Hodh El Gharbi", "Hodh El Gharbi"),
                            ("Hodh Ech Chargui", "Hodh Ech Chargui"),
                            ("Assaba", "Assaba"),
                            ("Gorgol", "Gorgol"),
                            ("Guidimaka", "Guidimaka"),
                            ("Adrar", "Adrar"),
                            ("Dakhlet Nouadhibou", "Dakhlet Nouadhibou"),
                            ("Tagant", "Tagant"),
                            ("Tiris Zemmour", "Tiris Zemmour"),
                            ("Inchiri", "Inchiri"),
                            ("Trarza", "Trarza"),
                        ],
                        max_length=50,
                        verbose_name="Wilaya",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Nouakchott", "Nouakchott"),
                            ("Nouadhibou", "Nouadhibou"),
                            ("Kiffa", "Kiffa"),
                            ("Rosso", "Rosso"),
                            ("Zouérat", "Zouérat"),
                            ("Atar", "Atar"),
                            ("Kaédi", "Kaédi"),
                            ("Aleg", "Aleg"),
                            ("Boutilimit", "Boutilimit"),
                            ("Selibaby", "Selibaby"),
                            ("Tidjikja", "Tidjikja"),
                            ("Néma", "Néma"),
                            ("Aïoun", "Aïoun"),
                            ("Sélibabi", "Sélibabi"),
                            ("Bogue", "Bogue"),
                            ("Mâl", "Mâl"),
                            ("Mbout", "Mbout"),
                            ("Timbedra", "Timbedra"),
                        ],
                        max_length=100,
                        verbose_name="Ville",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="Adresse complète"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pictures/%Y/%m/%d/",
                        verbose_name="Photo de profil",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biographie")),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Homme"),
                            ("female", "Femme"),
                            ("other", "Autre"),
                        ],
                        max_length=10,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "farm_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Nom de la ferme/exploitation",
                    ),
                ),
                (
                    "farm_size_hectares",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Superficie (hectares)",
                    ),
                ),
                (
                    "farm_location",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Localisation de la ferme",
                    ),
                ),
                (
                    "crop_types",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Types de cultures"
                    ),
                ),
                (
                    "farming_experience",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Années d'expérience"
                    ),
                ),
                (
                    "irrigation_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("goutte_a_goutte", "Goutte-à-goutte"),
                            ("aspersion", "Aspersion"),
                            ("gravitaire", "Gravitaire"),
                            ("manuelle", "Manuelle"),
                            ("aucun", "Aucun système"),
                        ],
                        max_length=50,
                        verbose_name="Système d'irrigation",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Compte vérifié"),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de vérification"
                    ),
                ),
                (
                    "is_active_farmer",
                    models.BooleanField(default=True, verbose_name="Agriculteur actif"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        verbose_name="Note moyenne",
                    ),
                ),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Chiffre d'affaires total",
                    ),
                ),
                (
                    "total_orders",
                    models.IntegerField(
                        default=0, verbose_name="Nombre total de commandes"
                    ),
                ),
                (
                    "completed_orders",
                    models.IntegerField(default=0, verbose_name="Commandes complétées"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("fr", "Français"), ("ar", "Arabe")],
                        default="fr",
                        max_length=10,
                        verbose_name="Langue préférée",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MRU", max_length=3, verbose_name="Devise préférée"
                    ),
                ),
                (
                    "receive_email_notifications",
                    models.BooleanField(
                        default=True,
                        verbose_name="Recevoir les notifications par email",
                    ),
                ),
                (
                    "receive_sms_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Recevoir les notifications par SMS"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        max_length=20,
                        verbose_name="Type d'appareil",
                    ),
                ),
                (
                    "device_token",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Token de l'appareil"
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID de l'appareil"
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Version de l'application",
                    ),
                ),
                (
                    "os_version",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Version du système d'exploitation",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Appareil actif"),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière utilisation"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appareil utilisateur",
                "verbose_name_plural": "Appareils utilisateurs",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secondary_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email secondaire"
                    ),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Téléphone secondaire"
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Profession"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom de l'entreprise"
                    ),
                ),
                (
                    "farm_registration_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Numéro d'enregistrement de la ferme",
                    ),
                ),
                (
                    "farm_certifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Certifications de la ferme",
                    ),
                ),
                (
                    "buyer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Particulier"),
                            ("restaurant", "Restaurant"),
                            ("hotel", "Hôtel"),
                            ("supermarket", "Supermarché"),
                            ("wholesaler", "Grossiste"),
                            ("other", "Autre"),
                        ],
                        default="individual",
                        max_length=50,
                        verbose_name="Type d'acheteur",
                    ),
                ),
                (
                    "preferred_product_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Catégories de produits préférées",
                    ),
                ),
                (
                    "preferred_delivery_time",
                    models.CharField(
                        choices=[
                            ("morning", "Matin (8h-12h)"),
                            ("afternoon", "Après-midi (14h-18h)"),
                            ("evening", "Soir (18h-22h)"),
                            ("anytime", "À tout moment"),
                        ],
                        default="anytime",
                        max_length=50,
                        verbose_name="Heure de livraison préférée",
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dernière IP de connexion"
                    ),
                ),
                (
                    "login_count",
                    models.IntegerField(default=0, verbose_name="Nombre de connexions"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière activité"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil utilisateur",
                "verbose_name_plural": "Profils utilisateurs",
            },
        ),
        migrations.CreateModel(
            name="UserVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_card_front",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="verification/id_cards/%Y/%m/%d/",
                        verbose_name="Recto de la carte d'identité",
                    ),
                ),
                (
                    "id_card_back",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="verification/id_cards/%Y/%m/%d/",
                        verbose_name="Verso de la carte d'identité",
                    ),
                ),
                (
                    "farm_registration_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="verification/farm_docs/%Y/%m/%d/",
                        verbose_name="Document d'enregistrement de la ferme",
                    ),
                ),
                (
                    "land_title_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="verification/land_docs/%Y/%m/%d/",
                        verbose_name="Titre de propriété",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("under_review", "En cours d'examen"),
                            ("verified", "Vérifié"),
                            ("rejected", "Rejeté"),
                            ("suspended", "Suspendu"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut de vérification",
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(blank=True, verbose_name="Notes de vérification"),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de vérification"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vérifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vérification utilisateur",
                "verbose_name_plural": "Vérifications utilisateurs",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["user_type"], name="accounts_us_user_ty_b6cfc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["wilaya", "city"], name="accounts_us_wilaya_87a452_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_verified"], name="accounts_us_is_veri_fa45d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["rating"], name="accounts_us_rating_658e53_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["created_at"], name="accounts_us_created_4734df_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userdevice",
            unique_together={("user", "device_token")},
        ),
    ]
