# Generated by Django 6.0.1 on 2026-01-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Accepté'), ('cancelled', 'Refusé'), ('shipped', 'Expédié'), ('delivered', 'Livré')], default='pending', max_length=20),
        ),
    ]
