# Generated by Django 6.0.1 on 2026-01-18 05:41

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_new_order", models.BooleanField(default=True)),
                ("email_order_updates", models.BooleanField(default=True)),
                ("email_payment", models.BooleanField(default=True)),
                ("email_marketing", models.BooleanField(default=False)),
                ("push_new_message", models.BooleanField(default=True)),
                ("push_order_updates", models.BooleanField(default=True)),
                ("push_weather_alerts", models.BooleanField(default=True)),
                ("push_system", models.BooleanField(default=True)),
                ("in_app_all", models.BooleanField(default=True)),
                ("sms_urgent", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence de notification",
                "verbose_name_plural": "Préférences de notification",
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.TextField(unique=True)),
                ("subscription_info", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement push",
                "verbose_name_plural": "Abonnements push",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("welcome", "Bienvenue"),
                            ("new_order", "Nouvelle commande"),
                            ("order_accepted", "Commande acceptée"),
                            ("order_shipped", "Commande expédiée"),
                            ("order_delivered", "Commande livrée"),
                            ("order_cancelled", "Commande annulée"),
                            ("new_message", "Nouveau message"),
                            ("weather_alert", "Alerte météo"),
                            ("low_stock", "Stock faible"),
                            ("new_review", "Nouvel avis"),
                            ("payment_received", "Paiement reçu"),
                            ("payout_sent", "Paiement envoyé"),
                            ("system", "Système"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "channels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("email", "Email"),
                                ("push", "Notification push"),
                                ("in_app", "Dans l'application"),
                                ("sms", "SMS"),
                            ],
                            max_length=20,
                        ),
                        default=list,
                    ),
                ),
                ("related_model", models.CharField(blank=True, max_length=50)),
                ("related_id", models.CharField(blank=True, max_length=100)),
                ("is_read", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("send_attempts", models.IntegerField(default=0)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "created_at"],
                        name="notificatio_user_id_8a7c6b_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "created_at"],
                        name="notificatio_notific_f2e0f7_idx",
                    ),
                ],
            },
        ),
    ]
