# Generated by Django 6.0.1 on 2026-01-18 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_customers", models.IntegerField(default=0)),
                (
                    "repeat_customer_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("total_products", models.IntegerField(default=0)),
                ("active_products", models.IntegerField(default=0)),
                ("best_selling_products", models.JSONField(default=list)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("total_reviews", models.IntegerField(default=0)),
                ("monthly_sales", models.JSONField(default=dict)),
                ("monthly_orders", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "farmer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Agriculteur",
                "verbose_name_plural": "Analytics Agriculteurs",
            },
        ),
    ]
