# Generated by Django 6.0.1 on 2026-01-18 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerWeatherPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_location", models.CharField(max_length=200)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("receive_rain_alerts", models.BooleanField(default=True)),
                ("receive_frost_alerts", models.BooleanField(default=True)),
                ("receive_storm_alerts", models.BooleanField(default=True)),
                ("receive_drought_alerts", models.BooleanField(default=True)),
                ("crop_types", models.JSONField(blank=True, default=list)),
                ("planting_date", models.DateField(blank=True, null=True)),
                ("harvest_date", models.DateField(blank=True, null=True)),
                (
                    "alert_threshold_rain",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                (
                    "alert_threshold_temp",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                (
                    "alert_threshold_wind",
                    models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
                ),
                (
                    "update_frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Chaque heure"),
                            ("3hours", "Toutes les 3 heures"),
                            ("6hours", "Toutes les 6 heures"),
                            ("daily", "Quotidien"),
                        ],
                        default="3hours",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "farmer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence météo agriculteur",
                "verbose_name_plural": "Préférences météo agriculteurs",
            },
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                ("feels_like", models.DecimalField(decimal_places=2, max_digits=5)),
                ("humidity", models.IntegerField()),
                ("pressure", models.IntegerField()),
                ("wind_speed", models.DecimalField(decimal_places=2, max_digits=5)),
                ("wind_direction", models.IntegerField()),
                ("weather_condition", models.CharField(max_length=100)),
                ("weather_icon", models.CharField(max_length=20)),
                ("visibility", models.IntegerField()),
                ("cloudiness", models.IntegerField()),
                ("sunrise", models.DateTimeField()),
                ("sunset", models.DateTimeField()),
                ("hourly_forecast", models.JSONField(blank=True, default=list)),
                ("daily_forecast", models.JSONField(blank=True, default=list)),
                (
                    "soil_moisture",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "precipitation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "uv_index",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("crop_suggestion", models.JSONField(blank=True, default=list)),
                ("irrigation_recommendation", models.TextField(blank=True)),
                ("pest_warning", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField()),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Donnée météo",
                "verbose_name_plural": "Données météo",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["location", "recorded_at"],
                        name="weather_wea_locatio_9322be_idx",
                    ),
                    models.Index(
                        fields=["latitude", "longitude", "recorded_at"],
                        name="weather_wea_latitud_8d6607_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WeatherAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("rain", "Pluie"),
                            ("storm", "Tempête"),
                            ("frost", "Gel"),
                            ("heat", "Canicule"),
                            ("drought", "Sécheresse"),
                            ("wind", "Vent fort"),
                            ("flood", "Inondation"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("moderate", "Modéré"),
                            ("high", "Élevé"),
                            ("severe", "Sévère"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("expected_start", models.DateTimeField()),
                ("expected_end", models.DateTimeField()),
                ("potential_impact", models.TextField()),
                ("recommendations", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_read", models.BooleanField(default=False)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("external_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "farmer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte météo",
                "verbose_name_plural": "Alertes météo",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["farmer", "is_active", "is_read"],
                        name="weather_wea_farmer__36e572_idx",
                    ),
                    models.Index(
                        fields=["alert_type", "severity"],
                        name="weather_wea_alert_t_5b595d_idx",
                    ),
                ],
            },
        ),
    ]
