# Generated by Django 6.0.1 on 2026-01-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmerreview",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
