# Generated by Django 6.0.1 on 2026-01-18 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diagnosis/', verbose_name='Image analysée')),
                ('disease', models.CharField(max_length=255, verbose_name='Maladie détectée')),
                ('confidence', models.FloatField(verbose_name='Taux de confiance (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date d’analyse')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agriculteur')),
            ],
            options={
                'verbose_name': 'Diagnostic',
                'verbose_name_plural': 'Diagnostics',
            },
        ),
    ]
